# Generated by Django 3.0.4 on 2020-03-23 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrymodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='state',
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 14, 0, 50, 586278), verbose_name='Last Update'),
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=70, null=True, verbose_name='State')),
                ('latitude', models.FloatField(default=0, null=True)),
                ('longitude', models.FloatField(default=0, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.CountryModel')),
            ],
        ),
        migrations.AddField(
            model_name='coviddatamodel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.StateModel'),
        ),
    ]
