# Generated by Django 3.0.4 on 2020-03-24 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrymodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='state',
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2011, 11, 4, 0, 5, 23, 283000, tzinfo=utc), verbose_name='Last Update'),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='latest_confirmed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='latest_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='latest_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 15, 35, 5, 834240), verbose_name='Last Update'),
        ),
    ]
