# Generated by Django 3.0.4 on 2020-03-22 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200322_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrymodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='countrymodel',
            name='state',
        ),
        migrations.AddField(
            model_name='coviddatamodel',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coviddatamodel',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coviddatamodel',
            name='state',
            field=models.CharField(max_length=70, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 11, 21, 664574), verbose_name='Last Update'),
        ),
    ]
