# Generated by Django 3.0.4 on 2020-03-24 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200324_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddatamodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 16, 4, 44, 839141, tzinfo=utc), verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='last_updated',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Last Update Day'),
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Last Update Day'),
        ),
    ]
