# Generated by Django 3.0.4 on 2020-03-22 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200322_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 26, 53, 429751), verbose_name='Last Update'),
        ),
    ]
