# Generated by Django 3.0.4 on 2020-03-23 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_auto_20200323_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 14, 2, 10, 278034), verbose_name='Last Update'),
        ),
    ]
