# Generated by Django 3.0.4 on 2020-03-22 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20200322_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 31, 21, 74489), verbose_name='Last Update'),
        ),
    ]
