# Generated by Django 3.0.4 on 2020-03-24 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_auto_20200324_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatamodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 16, 44, 20, 418400, tzinfo=utc), verbose_name='Last Update'),
        ),
    ]
