# Generated by Django 3.0.4 on 2020-03-22 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20200322_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddatamodel',
            name='_old_confirmed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coviddatamodel',
            name='new_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 18, 51, 52, 797907), verbose_name='Last Update'),
        ),
    ]
