# Generated by Django 3.0.4 on 2020-03-25 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20200325_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrymodel',
            name='new_cases',
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 14, 57, 40, 351588, tzinfo=utc), verbose_name='Last Update'),
        ),
    ]
