# Generated by Django 3.0.4 on 2020-03-23 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20200323_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 1, 1), verbose_name='Last Update'),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='latest_confirmed_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='latest_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='latest_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 14, 46, 17, 741217), verbose_name='Last Update'),
        ),
    ]
