# Generated by Django 3.0.4 on 2020-03-22 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20200322_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coviddatamodel',
            name='_old_confirmed_cases',
        ),
        migrations.RemoveField(
            model_name='coviddatamodel',
            name='new_cases',
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 19, 3, 17, 809133), verbose_name='Last Update'),
        ),
    ]
