# Generated by Django 3.0.4 on 2020-03-29 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0008_auto_20200325_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatamodel',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 7, 14, 34, 851758, tzinfo=utc), verbose_name='Last Update'),
        ),
    ]
