# Generated by Django 3.0.4 on 2020-03-23 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0013_auto_20200323_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 15, 23, 49, 606325), verbose_name='Last Update'),
        ),
    ]
