# Generated by Django 3.0.4 on 2020-03-23 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0014_auto_20200323_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=70, null=True, verbose_name='State')),
                ('latest_confirmed_cases', models.IntegerField(default=0)),
                ('latest_deaths', models.IntegerField(default=0)),
                ('latest_recovered', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2011, 11, 4, 0, 5, 23, 283000, tzinfo=utc), verbose_name='Last Update')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.CountryModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='coviddatamodel',
            name='state',
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 15, 40, 59, 83800), verbose_name='Last Update'),
        ),
        migrations.DeleteModel(
            name='StateModel',
        ),
        migrations.AddField(
            model_name='coviddatamodel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covid.CityModel'),
        ),
    ]
