# Generated by Django 3.0.4 on 2020-03-23 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0015_auto_20200323_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citymodel',
            name='state',
        ),
        migrations.AddField(
            model_name='citymodel',
            name='city',
            field=models.CharField(max_length=70, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='coviddatamodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 15, 41, 45, 921315), verbose_name='Last Update'),
        ),
    ]
